// AUTH ACTIONS

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const LOAD_AUTH_USER_START = 'LOAD_AUTH_USER_START'
export const LOAD_AUTH_USER_SUCCESS = 'LOAD_AUTH_USER_SUCCESS'

export const VERIFY_USER_START = 'VERIFY_USER_START'
export const VERIFY_USER_SUCCESFUL = 'VERIFY_USER_SUCCESFUL'
export const VERIFY_USER_FAILED = 'VERIFY_USER_FAILED'

export const RESEND_VERIFICATION_START = 'RESEND_VERIFICATION_START'
export const RESEND_VERIFICATION_SUCCESFUL = 'RESEND_VERIFICATION_SUCCESFUL'
export const RESEND_VERIFICATION_FAILED = 'RESEND_VERIFICATION_FAILED'

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const VERIFY_PAYMENT_START = 'VERIFY_PAYMENT_START'
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS'
export const VERIFY_PAYMENT_FAIL = 'VERIFY_PAYMENT_FAIL'

//USER ACTIONS

export const USER_START = 'USER_START'
export const USER_FAILED = 'USER_FAILED'
export const USER_SUCCESS = 'USER_SUCCESS'

export const ADD_USER_START = 'ADD_USER_START'
export const ADD_USER_FAILED = 'ADD_USER_FAILED'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESFUL = 'UPDATE_USER_SUCCESFUL'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

//ACCOUNT ACTIONS

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'

export const CHANGE_EMAIL_START = 'CHANGE_EMAIL_START'
export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL'
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS'

export const CHANGE_NAME_START = 'CHANGE_NAME_START'
export const CHANGE_NAME_FAIL = 'CHANGE_NAME_FAIL'
export const CHANGE_NAME_SUCCESS = 'CHANGE_NAME_SUCCESS'

export const CHANGE_PROFILE_IMAGE_START = 'CHANGE_PROFILE_IMAGE_START'
export const CHANGE_PROFILE_IMAGE_FAIL = 'CHANGE_PROFILE_IMAGE_FAIL'
export const CHANGE_PROFILE_IMAGE_SUCCESS = 'CHANGE_PROFILE_IMAGE_SUCCESS'

export const CHANGE_ANONYMITY_START = 'CHANGE_ANONYMITY_START'
export const CHANGE_ANONYMITY_FAIL = 'CHANGE_ANONYMITY_FAIL'
export const CHANGE_ANONYMITY_SUCCESS = 'CHANGE_ANONYMITY_SUCCESS'


//MESSAGE ACTIONS

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const GET_SUCCESS = 'GET_SUCCESS'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

//STUDENT ACTIONS

export const ADD_STUDENT_START = 'ADD_STUDENT_START'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL'

export const GET_ALL_STUDENTS_START = 'GET_ALL_STUDENTS_START'
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS'
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL'

export const DELETE_STUDENT_START = 'DELETE_STUDENT_START'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL'

export const VERIFY_STUDENT_START = 'VERIFY_STUDENT_START'
export const VERIFY_STUDENT_SUCCESS = 'VERIFY_STUDENT_SUCCESS'
export const VERIFY_STUDENT_FAIL = 'VERIFY_STUDENT_FAIL'

//Exam Actions

export const GET_EXAM_START = 'GET_EXAM_START'
export const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS'
export const GET_EXAM_FAIL = 'GET_EXAM_FAIL'


export const GET_SINGLE_EXAM_START = 'GET_SINGLE_EXAM_START'
export const GET_SINGLE_EXAM_SUCCESS = 'GET_SINGLE_EXAM_SUCCESS'
export const GET_SINGLE_EXAM_FAIL = 'GET_SINGLE_EXAM_FAIL'


export const UPLOAD_QUESTION_START = 'UPLOAD_QUESTION_START'
export const UPLOAD_QUESTION_SUCCESS = 'UPLOAD_QUESTION_SUCCESS'
export const UPLOAD_QUESTION_FAIL = 'UPLOAD_QUESTION_FAIL'



